version: "3.9"

volumes:
  static_files:
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/code
      - static_files:/static_files
    command: bash -c "cd code && gunicorn -w 4 mpsite.wsgi -b 0.0.0.0:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DSC_API_URL=http://milepogawedki.xyz:8080/
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    volumes:
      - static_files:/static_files
    ports:
      - "80:80"

